# Generated by Django 5.2.3 on 2025-07-02 17:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_berita_options_alter_kategori_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={},
        ),
        migrations.AlterField(
            model_name='berita',
            name='konten',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
