# Generated by Django 5.2.3 on 2025-07-03 02:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_berita_options_alter_kategori_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='konten',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
