# Generated by Django 5.2.3 on 2025-07-03 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_berita_konten'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': 'Kategori'},
        ),
    ]
