# Generated by Django 5.2.3 on 2025-07-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_kategori_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
