# Generated by Django 5.2.3 on 2025-07-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_berita_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/'),
        ),
    ]
